export const ADD_USER_DATA = 'ADD_USER_DATA';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
export const UPDATE_DATA = 'UPDATE_DATA';

export const ADD_NOTIFICATION_DATA = 'ADD_NOTIFICATION_DATA';
export const CLEAR_NOTIFICATION_DATA = 'CLEAR_NOTIFICATION_DATA';
export const UPDATE_NOTIFICATION_DATA = 'UPDATE_NOTIFICATION_DATA';

export const ADD_RIDE_DATA = 'ADD_RIDE_DATA';
export const CLEAR_RIDE_DATA = 'CLEAR_RIDE_DATA';
export const UPDATE_RIDE_DATA = 'UPDATE_RIDE_DATA';
